### ISSUE TITLE
backend complains of value mismatch when desired value never seen at frontend

### ISSUE THREAD

**Issue by jedirv** [SCAII/SCAII#10]
With the seed set to [3534880944, 3686270780, 3136535085, 4256128463]...

entity 7 starts off with a triangle shape.  Then some messages in, it gets replaced with a rectangle with height 3.932095766067505.  A few viz messages later, the height is changed to 5.617790222167969, but when I send back the next state message, an error complains that it was expecting height 5.4333124 as the height:

```
Sending a VizInit message
Protocol: We'll send you a ScaiiPacket delta, you apply it and send us your entity info (one ScaiiPacket in a MultiMessage).
Connection will be closed after a random number of ticks between 10 and 20, or with anerror message on desynchronization or incorrect response.
Sending a VizInit ScaiiPacket, no response expected
Sending first volley of entities to initialize list
thread 'main' panicked at 'Entity with id 7 does not match reference entity on server.
Got: IdEntity { entity: Entity { pos: Pos { x: 60.431442, y: 23.155186 }, shape: Shape { color: Color { r: 192, g: 22, b: 116, a: 218 }, relative_pos: Pos { x: 0, y: 0 }, shape: Rect { width: 3.7476182, height: 5.61779 } } }, id: 7 }, Expected: IdEntity { entity: Entity { pos: Pos { x: 60.431442, y: 23.155186 }, shape: Shape { color: Color { r: 192, g: 22, b: 116, a: 218 }, relative_pos: Pos { x: 0, y: 0 }, shape: Rect { width: 3.7476182, height: 5.4333124 } } }, id: 7 }
(NOTE: Floating point tolerance is: 0.0001', src\main.rs:263:20
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:379
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:396
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:611
   4: std::panicking::begin_panic_new<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:553
   5: rpc_viz::verify_scaii_packet
             at .\src\main.rs:263
   6: rpc_viz::test_loop<rand::XorShiftRng>
             at .\src\main.rs:475
   7: rpc_viz::test_viz_client
             at .\src\main.rs:497
   8: rpc_viz::main
             at .\src\main.rs:502
   9: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  10: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:52
  11: main
  12: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  13: BaseThreadInitThunk
error: process didn't exit successfully: `C:\Users\Jed Irvine\exact\SCAII\target\debug\rpc-viz.exe configuration.toml` (exit code: 101)
```

I've pushed my current code to the remote viz branch so you could pull that to replicate if needed.

Just start up the tester and then load up the file SCAII\viz\index.html into the (chrome or FF) browser

**Comment by jedirv** [comment]
this also happens (different numbers) when seed is set to: [1036904646, 1168543426, 1986032483, 3472759397]

**Comment by Jragonmiris** [comment]
I pushed an experimental change, but I can't get your program to run in my browser so I can't promise it works properly.

My suspicion is that it's another precision error since Javascript numbers are 64-bit floats, not 32-bit like we were using on the server and in the protobuf spec.

**Comment by Jragonmiris** [comment]
Note: you'll have to rerun the protobuf compiler for this change.

**Comment by jedirv** [comment]
Still getting mismatch on the height of the rectangle that is changing dimensions.
```
Got: IdEntity { entity: Entity { pos: Pos { x: 97.78217599351053, y: 86.04896316521062 }, shape: Shape { color: Color { r: 225, g: 7, b: 133, a: 248 }, relative_pos: Pos { x: 0, y: 0 }, shape: Rect { width: 0.6592139275912157, height: 1.202095961574872 } } }, id: 8 }, Expected: IdEntity { entity: Entity { pos: Pos { x: 97.78217599351053, y: 86.04896316521062 }, shape: Shape { color: Color { r: 225, g: 7, b: 133, a: 248 }, relative_pos: Pos { x: 0, y: 0 }, shape: Rect { width: 0.6592139275912157, height: 0.1 } } }, id: 8 }
```

**Comment by Jragonmiris** [comment]
I'll have to check it's possible that's my bad when I enforced nonnegative
values

**Comment by jedirv** [comment]
Fixed (-Zoe on Jed's computer)
